language: c
os:
 - linux
# - osx
install:
 - INSTALL_HERE="$(pwd)/libs"
 - LIBS_I="$INSTALL_HERE""/includes"
 - LIBS_L="$INSTALL_HERE""/objects"
 - . .travis/install_cmocka.sh
 - ls -R $INSTALL_HERE
before_script:
 - make build_dependencies
script:
 - make
 - make ut
